Before applying changes, please save the original Envoy proxy configuration following next steps:

[.console-input]
[source,input,subs="+macros,+attributes"]
----
oc exec <back-golang-pod_id> -c istio-proxy -n <user_namespace> curl localhost:15000/config_dump > {object}-config-init.json
----

.Envoy Configuration
image:02-envoy-istio-control-plane/{image_config_init}[link=../_images/02-envoy-istio-control-plane/{image_config_init},window=_blank]

It is time to modify a _{name}_ in order to see how it is implemented in Envoy proxy configuration through the respective configuration blocks:

:file: {file_repo}

include::oc_process_apply.adoc[]

.Modifed _{name}_ Configuration
image:02-envoy-istio-control-plane/{image}[link=../_images/02-envoy-istio-control-plane/{image},window=_blank]

Once this new _{name}_ has been modified, save the custom Envoy proxy configuration following next steps:

[.console-input]
[source,input,subs="+macros,+attributes"]
----
oc exec <back-golang-pod_id> -c istio-proxy -n <user_namespace> curl localhost:15000/config_dump > {object}-config-custom.json
----

Finally, compare both files differences and draw a definitive conclusion:

image:02-envoy-istio-control-plane/{image_config_compare}[link=../_images/02-envoy-istio-control-plane/{image_config_compare},window=_blank]