name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  SITE_DIR: "gh-pages"
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: site.yml
      - name: "Upload generated site"
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: [ubuntu-latest]
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download generated site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          # ACCESS_TOKEN: # optional
          token: "${{ github.token}}"
          folder: "${{ env.SITE_DIR }}"
          branch: "gh-pages"
          commit-message: "[CI] Publish Documentation for ${{ github.sha }}"
